CREATE TABLE IF NOT EXISTS weather_forecasts (
  id VARCHAR(36) NOT NULL,
  location_id VARCHAR(36) NOT NULL,
  forecast_date DATE NOT NULL,
  hour TINYINT,
  temp_min DECIMAL(5,2),
  temp_min_field DECIMAL(5,2),
  temp_max DECIMAL(5,2),
  temp_avg DECIMAL(5,2),
  humidity TINYINT,
  wind_speed DECIMAL(5,2),
  cloud_cover TINYINT,
  wind_direction VARCHAR(10),
  precipitation DECIMAL(5,2),
  `condition` VARCHAR(50),
  icon VARCHAR(20),
  uv_index TINYINT,
  frost_risk TINYINT DEFAULT 0,
  data_source VARCHAR(50),
  fetched_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE KEY uk_location_date_hour (location_id, forecast_date, hour),
  KEY idx_location_date (location_id, forecast_date),
  KEY idx_frost (frost_risk, forecast_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
